import type { ComAttribute } from "../attributeMap";

export const badgeAttribute: ComAttribute[] = [
  {
    label: "字段标识",
    propName: "comUUID",
    propValue: "",
    type: "input",
    defaultValue: "badge",
  },
  {
    label: "标题",
    propName: "label",
    propValue: "",
    type: "input",
    defaultValue: "徽标",
  },
  {
    label: "文字值",
    propName: "textValue",
    propValue: "",
    type: "input",
    defaultValue: "",
  },
  {
    label: "数字值",
    propName: "numberValue",
    propValue: "",
    type: "input-number",
    defaultValue: 0,
  },
  {
    label: "最大值",
    propName: "max",
    propValue: "",
    type: "input-number",
    defaultValue: 99,
  },
  {
    label: "显示数字",
    propName: "showNumber",
    propValue: "",
    type: "switch",
    defaultValue: true,
  },
  {
    label: "显示圆点",
    propName: "is-dot",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "隐藏徽标",
    propName: "hidden",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "徽标类型",
    propName: "type",
    propValue: "",
    type: "select",
    options: [
      { label: "primary", value: "primary" },
      { label: "success", value: "success" },
      { label: "warning", value: "warning" },
      { label: "danger", value: "danger" },
      { label: "info", value: "info" },
    ],
    defaultValue: "danger",
  },
  {
    label: "徽标颜色",
    propName: "color",
    propValue: "",
    type: "colorPicker",
    defaultValue: "",
  },
  {
    label: "X偏移量",
    propName: "leftOffset",
    propValue: "",
    type: "input-number-position",
    defaultValue: 0,
  },
  {
    label: "Y偏移量",
    propName: "topOffset",
    propValue: "",
    type: "input-number-position",
    defaultValue: 0,
  },
];
