import type { ComAttribute } from "../attributeMap";

export const descriptionsAttribute: ComAttribute[] = [
  {
    label: "字段标识",
    propName: "comUUID",
    propValue: "",
    type: "input",
    defaultValue: "descriptions",
  },
  {
    label: "标题",
    propName: "label",
    propValue: "",
    type: "input",
    defaultValue: "描述列表",
  },
  {
    label: "列表标题",
    propName: "content",
    propValue: "",
    type: "input",
    defaultValue: "User Info",
  },
  {
    label: "排列方向",
    propName: "direction",
    propValue: "",
    type: "radio-button",
    options: [
      { label: "vertical", value: "vertical" },
      { label: "horizontal", value: "horizontal" },
    ],
    defaultValue: "horizontal",
  },
  {
    label: "列表尺寸",
    propName: "size",
    propValue: "",
    type: "radio-button",
    options: [
      { label: "large", value: "large" },
      { label: "default", value: "default" },
      { label: "small", value: "small" },
    ],
    defaultValue: "default",
  },
  {
    label: "显示边框",
    propName: "border",
    propValue: "",
    type: "switch",
    defaultValue: true,
  },
  {
    label: "列表数据",
    propName: "desColData",
    propValue: "",
    type: "desColData",
    defaultValue: [
      {
        label: "User Info",
        content: "kooriookami",
        align: "",
        span: 1,
        width: 0,
        rowSpan: 1,
        icon: "",
        labelAlign: "",
      },
      {
        label: "Telephone",
        content: "18100000000",
        align: "",
        span: 1,
        width: 0,
        rowSpan: 1,
        icon: "Iphone",
        labelAlign: "",
      },
      {
        label: "Place",
        content: "Suzhou",
        align: "",
        span: 1,
        width: 0,
        rowSpan: 1,
        icon: "Location",
        labelAlign: "",
      },
    ],
  },
  {
    label: "列数",
    propName: "column",
    propValue: "",
    type: "input-number-position",
    defaultValue: 1,
  },
];
