import type { ComAttribute } from "../attributeMap";

export const progressAttribute: ComAttribute[] = [
  {
    label: "字段标识",
    propName: "comUUID",
    propValue: "",
    type: "input",
    defaultValue: "progress",
  },
  {
    label: "标题",
    propName: "label",
    propValue: "",
    type: "input",
    defaultValue: "进度条",
  },
  {
    label: "百分比",
    propName: "percentage",
    propValue: "1to100",
    type: "input-number",
    defaultValue: 50,
  },
  {
    label: "进度条长度",
    propName: "max",
    propValue: "min0",
    type: "input-number",
    defaultValue: 300,
  },
  {
    label: "进度条宽度",
    propName: "stroke-width",
    propValue: "",
    type: "input-number",
    defaultValue: 6,
  },
  {
    label: "进度条类型",
    propName: "type",
    propValue: "",
    type: "radio-button",
    options: [
      { label: "线型", value: "line" },
      { label: "圆型", value: "circle" },
      { label: "仪表盘", value: "dashboard" },
    ],
    defaultValue: "line",
  },
  {
    label: "进度条状态",
    propName: "status",
    propValue: "",
    type: "radio-button",
    options: [
      { label: "默认", value: "" },
      { label: "成功", value: "success" },
      { label: "警告", value: "warning" },
      { label: "危险", value: "exception" },
    ],
    defaultValue: "",
  },
  {
    label: "显示文字",
    propName: "show-text",
    propValue: "",
    type: "switch",
    defaultValue: true,
  },
  {
    label: "文字内置",
    propName: "text-inside",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "动画进度条",
    propName: "indeterminate",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "动画时间",
    propName: "duration",
    propValue: "1to100",
    type: "input-number",
    defaultValue: 3,
  },
  {
    label: "条纹进度条",
    propName: "striped",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "自定义颜色",
    propName: "color",
    propValue: "",
    type: "colorPicker",
    defaultValue: "",
  },
];
