import type { ComAttribute } from "../attributeMap";

export const sliderAttribute: ComAttribute[] = [
  {
    label: "字段标识",
    propName: "comUUID",
    propValue: "",
    type: "input",
    defaultValue: "slider",
  },
  {
    label: "标题",
    propName: "label",
    propValue: "",
    type: "input",
    defaultValue: "滑块",
  },
  {
    label: "当前值",
    propName: "content",
    propValue: "",
    type: "input-number",
    defaultValue: 0,
  },
  {
    label: "最小值",
    propName: "min",
    propValue: "min0",
    type: "input-number",
    defaultValue: 0,
  },
  {
    label: "最大值",
    propName: "max",
    propValue: "min0",
    type: "input-number",
    defaultValue: 100,
  },
  {
    label: "步长",
    propName: "step",
    propValue: "",
    type: "input-number",
    defaultValue: 1,
  },
  {
    label: "滑块尺寸",
    propName: "sliderSize",
    propValue: "",
    type: "radio-button",
    options: [
      { label: "大型", value: "large" },
      { label: "默认", value: "" },
    ],
    defaultValue: "",
  },

  {
    label: "显示间隔",
    propName: "show-stops",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "选择范围",
    propName: "range",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "显示提示",
    propName: "show-tooltip",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "提示位置",
    propName: "placement",
    propValue: "",
    type: "radio-button",
    options: [
      { label: "上", value: "top" },
      { label: "下", value: "bottom" },
      { label: "左", value: "left" },
      { label: "右", value: "right" },
    ],
    defaultValue: "top",
  },
  {
    label: "显示输入框",
    propName: "show-input",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "垂直模式",
    propName: "vertical",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
  {
    label: "滑块高度",
    propName: "sliderHeight",
    propValue: "",
    type: "input-number",
    defaultValue: 0,
  },
  {
    label: "滑块长度",
    propName: "sliderWidth",
    propValue: "",
    type: "input-number",
    defaultValue: 300,
  },
  {
    label: "禁用状态",
    propName: "disabled",
    propValue: "",
    type: "switch",
    defaultValue: false,
  },
];
